# Generated by Django 5.2.1 on 2025-07-31 02:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0002_news_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
