# Generated by Django 5.2.1 on 2025-07-31 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0003_alter_news_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
