# Generated by Django 5.2.1 on 2025-07-31 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('رياضى', 'رياضى'), ('مقالى', 'مقالى')], default='مقالى', max_length=10),
        ),
    ]
