# Generated by Django 5.2.1 on 2025-07-31 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0005_news_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('رياضى', 'رياضى'), ('مقالى', 'مقالى'), ('اخر', 'اخر')], default='مقالى', max_length=10),
        ),
    ]
