# Generated by Django 5.2.1 on 2025-08-07 11:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0007_alter_news_category_alter_news_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='وصف الخبر'),
        ),
    ]
