# Generated by Django 5.2.1 on 2025-08-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0009_newsimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='خبر مميز'),
        ),
    ]
