# Generated by Django 5.2.1 on 2025-08-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0011_alter_news_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='وصف الخبر'),
        ),
    ]
