# Generated by Django 5.2.1 on 2025-08-08 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0012_alter_news_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsImage',
        ),
    ]
