# Generated by Django 5.2.1 on 2025-08-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0013_delete_newsimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('رياضى', 'رياضى'), ('مقالى', 'مقالى'), ('اخر', 'اخر')], default='اخر', max_length=10, verbose_name='التصنيف'),
        ),
    ]
